# Generated by Django 4.1.7 on 2026-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
    ]
